### ISSUE TITLE
how to mitigate this

### ISSUE THREAD

**Issue by NekoRem** [Zpes/anti-anti-debug#1]
a simple way to mitigate this would be to check if the function has been modified
credits to https://habr.com/en/post/178183/
```
bool IsDebuggerPresent()
{
    HMODULE hKernel32 = GetModuleHandleA("kernel32.dll");
    if (!hKernel32)
        return false;
    FARPROC pIsDebuggerPresent = GetProcAddress(hKernel32, "IsDebuggerPresent");
    if (!pIsDebuggerPresent)
        return false;

    HANDLE hSnapshot = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
    if (INVALID_HANDLE_VALUE == hSnapshot)
        return false;

    PROCESSENTRY32W ProcessEntry;
    ProcessEntry.dwSize = sizeof(PROCESSENTRY32W);

    if (!Process32FirstW(hSnapshot, &ProcessEntry))
        return false;

    bool bDebuggerPresent = false;
    HANDLE hProcess = NULL;
    DWORD dwFuncBytes = 0;
    const DWORD dwCurrentPID = GetCurrentProcessId();
    do
    {
        __try
        {
            if (dwCurrentPID == ProcessEntry.th32ProcessID)
                continue;

            hProcess = OpenProcess(PROCESS_ALL_ACCESS, FALSE, ProcessEntry.th32ProcessID);
            if (NULL == hProcess)
                continue;

            if (!ReadProcessMemory(hProcess, pIsDebuggerPresent, &dwFuncBytes, sizeof(DWORD), NULL))
                continue;

            if (dwFuncBytes != *(PDWORD)pIsDebuggerPresent)
            {
                bDebuggerPresent = true;
                break;
            }
        }
        __finally
        {
            if (hProcess)
                CloseHandle(hProcess);
        }
    } while (Process32NextW(hSnapshot, &ProcessEntry));

    if (hSnapshot)
        CloseHandle(hSnapshot);
    return bDebuggerPresent;
}
```

**Comment by Zpes** [comment]
if u gon be doing that then i can also just directly flip the bit in the peb. the whole point of this repo is the basics of the anti anti-debugger cycle. the worst thing is, this code would not even work. you are "integrity checking" kernel32.dll IsDebuggerPresent (wich just calls the kernelbase IsDebuggerPresent). so this code you send wouldnt even work. because I am patching in the kernelbase.dll. clearly did not read the code through.

**Comment by NekoRem** [comment]
> if u gon be doing that then i can also just directly flip the bit in the peb. the whole point of this repo is the basics of the anti anti-debugger cycle. the worst thing is, this code would not even work. you are "integrity checking" kernel32.dll IsDebuggerPresent (wich just calls the kernelbase IsDebuggerPresent). so this code you send wouldnt even work. because I am patching in the kernelbase.dll. clearly did not read the code through.

Apologies just going through random repos and i guess i read it wrong... After a second inspection it seems you're right!
